#!/bin/sh

sudo rm -fR fsimage/usr/share/calendar fsimage/usr/share/doc fsimage/usr/share/doc-base  \
 fsimage/usr/share/locale/oc \
 fsimage/usr/share/locale/bs \
 fsimage/usr/share/locale/de_CH \
 fsimage/usr/share/locale/ta \
 fsimage/usr/share/locale/nl \
 fsimage/usr/share/locale/es_ES \
 fsimage/usr/share/locale/cy \
 fsimage/usr/share/locale/pt \
 fsimage/usr/share/locale/sq \
 fsimage/usr/share/locale/gu \
 fsimage/usr/share/locale/rw \
 fsimage/usr/share/locale/pt_PT \
 fsimage/usr/share/locale/mk \
 fsimage/usr/share/locale/sv \
 fsimage/usr/share/locale/ne \
 fsimage/usr/share/locale/zh_HK \
 fsimage/usr/share/locale/sk \
 fsimage/usr/share/locale/hu \
 fsimage/usr/share/locale/id \
 fsimage/usr/share/locale/ru \
 fsimage/usr/share/locale/az \
 fsimage/usr/share/locale/mn \
 fsimage/usr/share/locale/wo \
 fsimage/usr/share/locale/gl \
 fsimage/usr/share/locale/nb \
 fsimage/usr/share/locale/it \
 fsimage/usr/share/locale/hu_HU \
 fsimage/usr/share/locale/pa \
 fsimage/usr/share/locale/ms \
 fsimage/usr/share/locale/ast \
 fsimage/usr/share/locale/bg \
 fsimage/usr/share/locale/fr \
 fsimage/usr/share/locale/be@latin \
 fsimage/usr/share/locale/mr \
 fsimage/usr/share/locale/da \
 fsimage/usr/share/locale/eo \
 fsimage/usr/share/locale/hi \
 fsimage/usr/share/locale/ml \
 fsimage/usr/share/locale/nn \
 fsimage/usr/share/locale/de_AT \
 fsimage/usr/share/locale/ko \
 fsimage/usr/share/locale/fr_FR \
 fsimage/usr/share/locale/es \
 fsimage/usr/share/locale/de \
 fsimage/usr/share/locale/mg \
 fsimage/usr/share/locale/hr \
 fsimage/usr/share/locale/ka \
 fsimage/usr/share/locale/ku \
 fsimage/usr/share/locale/vi \
 fsimage/usr/share/locale/th \
 fsimage/usr/share/locale/eu \
 fsimage/usr/share/locale/ca \
 fsimage/usr/share/locale/be-tarask \
 fsimage/usr/share/locale/he \
 fsimage/usr/share/locale/km \
 fsimage/usr/share/locale/wa \
 fsimage/usr/share/locale/ro \
 fsimage/usr/share/locale/fi \
 fsimage/usr/share/locale/be \
 fsimage/usr/share/locale/ja \
 fsimage/usr/share/locale/et \
 fsimage/usr/share/locale/ar \
 fsimage/usr/share/locale/lt \
 fsimage/usr/share/locale/dz \
 fsimage/usr/share/locale/tr \
 fsimage/usr/share/locale/tl \
 fsimage/usr/share/locale/sl \
 fsimage/usr/share/locale/kk \
 fsimage/usr/share/locale/zh_CN \
 fsimage/usr/share/locale/lv \
 fsimage/usr/share/locale/sr \
 fsimage/usr/share/locale/is \
 fsimage/usr/share/locale/ga \
 fsimage/usr/share/locale/pl \
 fsimage/usr/share/locale/zh_TW \
 fsimage/usr/share/locale/cs \
 fsimage/usr/share/locale/pt_BR \
 fsimage/usr/share/locale/uk \
 fsimage/usr/share/locale/de_DE \
 fsimage/usr/share/locale/te \
 fsimage/usr/share/locale/el \
 fsimage/usr/share/locale/sw \
 fsimage/usr/share/locale/bn \
 fsimage/usr/share/locale/rm \
 fsimage/usr/share/locale/nds \
 fsimage/var/log/* fsimage/var/cache/* fsimage/var/apt/* fsimage/var/dpkg/* 

