#!/bin/sh

sudo rm -fR live-image/usr/share/calendar live-image/usr/share/doc live-image/usr/share/doc-base  \
 live-image/usr/share/locale/oc \
 live-image/usr/share/locale/bs \
 live-image/usr/share/locale/de_CH \
 live-image/usr/share/locale/ta \
 live-image/usr/share/locale/nl \
 live-image/usr/share/locale/es_ES \
 live-image/usr/share/locale/cy \
 live-image/usr/share/locale/pt \
 live-image/usr/share/locale/sq \
 live-image/usr/share/locale/gu \
 live-image/usr/share/locale/rw \
 live-image/usr/share/locale/pt_PT \
 live-image/usr/share/locale/mk \
 live-image/usr/share/locale/sv \
 live-image/usr/share/locale/ne \
 live-image/usr/share/locale/zh_HK \
 live-image/usr/share/locale/sk \
 live-image/usr/share/locale/hu \
 live-image/usr/share/locale/id \
 live-image/usr/share/locale/ru \
 live-image/usr/share/locale/az \
 live-image/usr/share/locale/mn \
 live-image/usr/share/locale/wo \
 live-image/usr/share/locale/gl \
 live-image/usr/share/locale/nb \
 live-image/usr/share/locale/it \
 live-image/usr/share/locale/hu_HU \
 live-image/usr/share/locale/pa \
 live-image/usr/share/locale/ms \
 live-image/usr/share/locale/ast \
 live-image/usr/share/locale/bg \
 live-image/usr/share/locale/fr \
 live-image/usr/share/locale/be@latin \
 live-image/usr/share/locale/mr \
 live-image/usr/share/locale/da \
 live-image/usr/share/locale/eo \
 live-image/usr/share/locale/hi \
 live-image/usr/share/locale/ml \
 live-image/usr/share/locale/nn \
 live-image/usr/share/locale/de_AT \
 live-image/usr/share/locale/ko \
 live-image/usr/share/locale/fr_FR \
 live-image/usr/share/locale/es \
 live-image/usr/share/locale/de \
 live-image/usr/share/locale/mg \
 live-image/usr/share/locale/hr \
 live-image/usr/share/locale/ka \
 live-image/usr/share/locale/ku \
 live-image/usr/share/locale/vi \
 live-image/usr/share/locale/th \
 live-image/usr/share/locale/eu \
 live-image/usr/share/locale/ca \
 live-image/usr/share/locale/be-tarask \
 live-image/usr/share/locale/he \
 live-image/usr/share/locale/km \
 live-image/usr/share/locale/wa \
 live-image/usr/share/locale/ro \
 live-image/usr/share/locale/fi \
 live-image/usr/share/locale/be \
 live-image/usr/share/locale/ja \
 live-image/usr/share/locale/et \
 live-image/usr/share/locale/ar \
 live-image/usr/share/locale/lt \
 live-image/usr/share/locale/dz \
 live-image/usr/share/locale/tr \
 live-image/usr/share/locale/tl \
 live-image/usr/share/locale/sl \
 live-image/usr/share/locale/kk \
 live-image/usr/share/locale/zh_CN \
 live-image/usr/share/locale/lv \
 live-image/usr/share/locale/sr \
 live-image/usr/share/locale/is \
 live-image/usr/share/locale/ga \
 live-image/usr/share/locale/pl \
 live-image/usr/share/locale/zh_TW \
 live-image/usr/share/locale/cs \
 live-image/usr/share/locale/pt_BR \
 live-image/usr/share/locale/uk \
 live-image/usr/share/locale/de_DE \
 live-image/usr/share/locale/te \
 live-image/usr/share/locale/el \
 live-image/usr/share/locale/sw \
 live-image/usr/share/locale/bn \
 live-image/usr/share/locale/rm \
 live-image/usr/share/locale/nds \
 live-image/var/apt/* live-image/var/dpkg/* 

