#!/bin/bash

# Author: Naoyuki Tai
# License: Creative Common
# Description: 

# Load DRBL setting and functions
DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/opt/drbl/}"

. $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
. $DRBL_SCRIPT_PATH/conf/drbl-ocs.conf
. $DRBL_SCRIPT_PATH/sbin/ocs-functions

# load the setting for clonezilla live.
[ -e /etc/ocs/ocs-live.conf ] && . /etc/ocs/ocs-live.conf

# Get the live media mount point.
get_live_media_mnt_point

# prepare the clonezilla live environment.
ocs-live-env-prepare

LC_ALL=$ocs_lang /usr/bin/python $ocs_live_extra_param


