#!/bin/bash

# Author: Naoyuki Tai
# License: Creative Common
# Description: 

DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"

. $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
. /etc/drbl/drbl-ocs.conf
. $DRBL_SCRIPT_PATH/sbin/ocs-functions

# load the setting for clonezilla live.
[ -e /etc/ocs/ocs-live.conf ] && . /etc/ocs/ocs-live.conf

# Functions
USAGE() {
    echo "Usage: /wce.py"
} # end of USAGE

LC_ALL=$ocs_lang /usr/bin/python $ocs_live_extra_param

